// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://unfdmncgltzcgpnaenvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVuZmRtbmNnbHR6Y2dwbmFlbnZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzOTI1MTksImV4cCI6MjA4NTk2ODUxOX0.V9HfcjZM4wAuzULGP4gzblosOeiQET0OLJ4mpX6u-Mw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});